# This is a simple gitlab continuous integration example project (compatible with the shared runner provided on gitlab.com)
# using the official debian linux based dotnet docker image to build a .NET Core project.
#
# MyProject.sln
#   MyProject\
#      MyProject.csproj (console application)
#   MyProject.Test\
#      MyProject.Test.csproj (test library)
#
# Please find the full example project here:
# https://gitlab.com/tobiaskoch/gitlab-ci-example-dotnetcore

# see https://hub.docker.com/r/microsoft/dotnet/

#https://github.com/t081as/gitlab-ci-example-dotnetcore
#https://gitlab.com/jelleverheyen/dotnet-ci-example/blob/master/.gitlab-ci.yml
#https://git.cdc.gov/help/ci/quick_start/README


image: ubuntu:18.04


stages:
    - build


variables:
    test: "Example.Test"

before_script:
    #- "cd source-code/mmria/mmria-server"
    #- "dotnet restore mmria-server.csproj"

build:
    stage: build
    script:
#        - "dotnet build  mmria-server.csproj /p:Configuration=Release /t:Clean"
#        - "curl -X POST -k https://ecpaas-dev.cdc.gov/apis/build.openshift.io/v1/namespaces/mmria/buildconfigs/mmria-s2i/webhooks/52dee2e0318578c7/generic"
        - echo "---> Version Setup - Begin ..."
        - apt-get update && apt-get install -y curl
        - current_year=$(date +%y)
        - current_month=$(date +%m)
        - current_day=$(date +%d)
        - curl https://github.com/icuseven/MMRDS/commits/master | grep -E "commit/([0-9abcdef]{40})"  > commit_temp.txt
        - current_build=$(cat commit_temp.txt | head -n1 | cut -d "/" -f7  | awk '{print substr ($0, 0, 7)}')
        - full_commit_number=$(cat commit_temp.txt | head -n1 | cut -d "/" -f7  | awk '{print substr ($0, 0, 40)}')
        - echo "---> $current_year.$current_month.$current_day v($current_build)"
        - version_text="$current_year.$current_month.$current_day v($current_build)"
        - echo "$version_text"
        - echo "---> Version Setup - End ..."
        - 'curl -H "Content-Type: application/json" -X POST \'
        -  -d ' \  
        -  '{ \'
        -  '    "ApplicationData":{ \'
        -  '        "ReleaseId":0, \'
        -  '        "ApplicationName":"Test_App", \'
        -  '        "ReleaseName":"Release 1", \'
        -  '        "CodeLocation":"https://github.com/icuseven/MMRDS.git", \'
        -  '        "CommitOrChangesetNumber":"$full_commit_number", \'
        -  '        "EnvironmentDeployed":"Dev", \'
        -  '        "UserDeployed":"Haines III, James E. (CDC DDNID NCCDPHP OD) (CTR)", \'
        -  '        "ApplicationURL":"http://test-mmria.services-dev.cdc.gov" \'
        -  '    }, \'
        -  '    "ScansToRun":[ \'
        -  '        { \'
        -  '            "ScanName":"Fortify", \'
        -  '            "ScanParameters":{ \'
        -  '                "BuildConfiguration":"", \'
        -  '                "CodeRepoType":"GIT", \'
        -  '                "SolutionFileName":"", \'
        -  '                "SSCApplicationName":"NCCD_Maternal Mortality Review Information App", \'
        -  '                "SSCApplicationVersion":"CSharp", \'
        -  '                "Technology":"CSharp" \'
        -  '            } \'
        -  '        } \'
        # -  '        ,{ \'
        # -  '            "ScanName":"WebInspect", \'
        # -  '            "ScanParameters":{ \'
        # -  '                "ApplicationPassword":"testPass", \'
        # -  '                "ApplicationUsername":"testUser", \'
        # -  '                "AuthenticationType":"None", \'
        # -  '                "MacroName":"testMacro", \'
        # -  '                "SSCApplicationName":"NCCD_DPRP_Data_Portal/User_UI (Public)", \'
        # -  '                "SSCApplicationVersion":"Javascript", \'
        # -  '                "StartingURL":"https://server.cdc.gov/application" \'
        # -  '            } \'
        # -  '        } \'
        -  '         \'
        -  '    ]} \'
        -  \'
        -  https://nccdgisdev.cdc.gov/TeamAutomation/RunBuilds
